# Generated by Django 5.0.3 on 2024-04-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0002_alter_transaction_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rfid_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(default='a628bf53a68d4152986ee70a1c1b6b6e', max_length=255, unique=True),
        ),
    ]
